// extracted from https://satisfactory.fandom.com/wiki/Category:Items
export const itemNames = [
    'Adaptive Control Unit',
    'AI Limiter',
    'Alclad Aluminum Sheet',
    'Alien Carapace',
    'Aluminum Casing',
    'Aluminum Ingot',
    'Aluminum Scrap',
    'Assembly Director System',
    'Automated Wiring',
    'Bacon Agaric',
    'Battery',
    'Bauxite',
    'Beacon',
    'Beryl Nut',
    'Biomass',
    'Black Powder',
    'Blade Runners',
    'Cable',
    'Caterium Ingot',
    'Caterium Ore',
    'Circuit Board',
    'Coal',
    'Color Gun',
    'Compacted Coal',
    'Computer',
    'Concrete',
    'Cooling System',
    'Copper Ingot',
    'Copper Ore',
    'Copper Powder',
    'Copper Sheet',
    'Crude Oil',
    'Crystal Oscillator',
    'Cup',
    'Electromagnetic Control Rod',
    'Empty Canister',
    'Empty Fluid Tank',
    'Encased Industrial Beam',
    'Encased Plutonium Cell',
    'Encased Uranium Cell',
    'Fabric',
    'FICSIT Coupon',
    'Flower Petals',
    'Fused Modular Frame',
    'Gas Mask',
    'Hard Drive',
    'Hazmat Suit',
    'Heat Sink',
    'Heavy Modular Frame',
    'High-Speed Connector',
    'Hover Pack',
    'HUB Parts',
    'Iron Ingot',
    'Iron Ore',
    'Iron Plate',
    'Iron Rod',
    'Jetpack',
    'Leaves',
    'Limestone',
    'Magnetic Field Generator',
    'Medicinal Inhaler',
    'Mercer Sphere',
    'Modular Engine',
    'Modular Frame',
    'Motor',
    'Mycelia',
    'Non-fissile Uranium',
    'Nuclear Pasta',
    'Object Scanner',
    'Packaged Alumina Solution',
    'Packaged Fuel',
    'Packaged Heavy Oil Residue',
    'Packaged Liquid Biofuel',
    'Packaged Nitric Acid',
    'Packaged Nitrogen Gas',
    'Packaged Oil',
    'Packaged Sulfuric Acid',
    'Packaged Turbofuel',
    'Packaged Water',
    'Paleberry',
    'Parachute',
    'Petroleum Coke',
    'Plastic',
    'Plutonium Fuel Rod',
    'Plutonium Pellet',
    'Plutonium Waste',
    'Polymer Resin',
    'Power Shard',
    'Power Slug',
    'Pressure Conversion Cube',
    'Quantum Computer',
    'Quartz Crystal',
    'Quickwire',
    'Radio Control Unit',
    'Raw Quartz',
    'Rebar Gun',
    'Reinforced Iron Plate',
    'Rifle',
    'Rotor',
    'Rubber',
    'SAM Ore',
    'Screw',
    'Silica',
    'Smart Plating',
    'Solid Biofuel',
    'Somersloop',
    'Stator',
    'Statue',
    'Steel Beam',
    'Steel Ingot',
    'Steel Pipe',
    'Sulfur',
    'Supercomputer',
    'Superposition Oscillator',
    'Thermal Propulsion Rocket',
    'Turbo Motor',
    'Turbofuel',
    'Uranium',
    'Uranium Fuel Rod',
    'Uranium Waste',
    'Versatile Framework',
    'Vines',
    'Wire',
    'Wood',
    'Xeno-Basher',
    'Xeno-Zapper',
    'Zipline',
];
